name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  STICKY_LINT_MESSAGE_ID: lint-failure
  STICKY_BUILD_AND_TEST_MESSAGE_ID: test-or-failure

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository ⏬
        uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js 💿
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies 💤
        run: pnpm install

      - name: Run linting 🧹
        id: linting
        run: pnpm lint:check --output-file=eslint-report.json --format=json

      - name: Generate comment about lint results
        if: always() && steps.linting.outcome == 'failure'
        id: lint-comment
        uses: ./.github/actions/eslint-comment-result
        with:
          eslint-output-path: eslint-report.json

      - name: Report failure
        if: always() && steps.linting.outcome == 'failure'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ${{ env.STICKY_LINT_MESSAGE_ID }}
          message: ${{ steps.lint-comment.outputs.message }}
          recreate: true

      - name: Remove last test failure message
        if: always() && steps.linting.outcome != 'failure'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ${{ env.STICKY_LINT_MESSAGE_ID }}
          delete: true

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository ⏬
        uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js 💿
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies 💤
        run: pnpm install

      - name: Build the app 👷‍♂️
        run: pnpm -F app build

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2]
    steps:
      - name: Check out Git repository ⏬
        uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js 💿
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies 💤
        run: pnpm install

      - name: Run tests 🧪
        run: pnpm -F app jest --shard=${{ matrix.shard }}/2

  test-result-summary:
    name: Summarize test job results
    runs-on: ubuntu-latest
    needs: [test]
    if: always()
    steps:
      - name: Return with an error status if any of the test shards failed
        if: needs.test.result == 'failure'
        run: exit 1

  build-and-test-failure-report:
    name: Reports the failure of the build or the test job
    runs-on: ubuntu-latest
    needs: [build, test-result-summary]
    if: always()
    steps:
      - name: Report build and test failure
        if: needs.test-result-summary.result == 'failure' && needs.build.result == 'failure'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ${{ env.STICKY_BUILD_AND_TEST_MESSAGE_ID }}
          message: |
            ### <img src="https://api.iconify.design/logos:typescript-icon.svg" height="24" align="top" /> <img src="https://api.iconify.design/logos:jest.svg" height="24" align="top" /> Both building the app and it's tests have failed ❌

            For more details, see the workflow output: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            > [!NOTE]
            > It is very likely that the test are failing because of the build error. We recommend checking that out first.

            > [!IMPORTANT]
            > If the build error is **not related to the changes made in your PR**, please check out the master branch and if the build is failing there as well, **write a slack message for us in the [#channel]()** and we're going to fix the issue as soon as possible.
          recreate: true

      - name: Report build failure
        if: needs.test-result-summary.result != 'failure' && needs.build.result == 'failure'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ${{ env.STICKY_BUILD_AND_TEST_MESSAGE_ID }}
          message: |
            ### <img src="https://api.iconify.design/logos:typescript-icon.svg" height="24" align="top" /> Building the App Failed ❌

            For details, see the workflow output: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            > [!IMPORTANT]
            > If the error is **not related to the changes made in your PR**, please check out the master branch and if the build is failing there as well, **write a slack message for us in the [#channel]()** and we're going to fix the issue as soon as possible.
          recreate: true

      - name: Report test failure
        if: needs.test-result-summary.result == 'failure' && needs.build.result != 'failure'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ${{ env.STICKY_BUILD_AND_TEST_MESSAGE_ID }}
          message: |
            ### <img src="https://api.iconify.design/logos:jest.svg" height="24" align="top" /> Tests Failed ❌

            For more details, see the workflow output: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          recreate: true

      - name: Remove last failure message if everything is right
        if: needs.test-result-summary.result != 'failure' && needs.build.result != 'failure'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ${{ env.STICKY_BUILD_AND_TEST_MESSAGE_ID }}
          delete: true
